---
destination : ./_site/
lsi         : false
highlight   : pygment
permalink   : none
markdown    : kramdown

maruku:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : assets/images/latex/
    png_url    : /assets/images/latex/

images: /assets/images/

gmail: jiangchunheng@gmail.com
horsehour: http://www.horsehour.com
github: https://github.com/horsehour
linkedin: https://www.linkedin.com/in/jiangch/

pdf: /assets/images/pdf.png
gt: /assets/images/git.png
py: /assets/images/python.png
java: /assets/images/java.png

theme: jekyll-theme-time-machine
